### ISSUE TITLE
Loose semi-column?

### ISSUE THREAD

**Issue by phiw13** [Bloke/smd_thumbnail#12]
In the category of really minor issues: [Here](https://github.com/Bloke/smd_thumbnail/blob/master/smd_thumbnail.php#L211)

```
.smd_thumb_switcher { float:right; margin: 0.8rem 0.6rem; 0.5rem}
```

Either the semi-column is misplaced or the `0.5rem` is not needed.

**Comment by philwareham** [comment]
I am currently redoing the layout of this plugin and this issue should be fixed by it. PR to be merged soon (once I've ironed out a few kinks).
