### ISSUE TITLE
Tag error: Undefined variable: alt

### ISSUE THREAD

**Issue by philwareham** [Bloke/smd_thumbnail#23]
Hi Stef, I'm getting a tag error message with the following code:

    <txp:images>
        <p itemprop="image" itemscope itemtype="http://schema.org/ImageObject">
            <txp:smd_if_thumbnail type="article-832w">
                <txp:smd_thumbnail type="article-832w">
                    <img itemprop="url" alt="<txp:image_info type='alt' />" src="<txp:smd_thumbnail_info item="url" />" srcset="<txp:image_url /> 2x, <txp:smd_thumbnail_info item="url" /> 1x">
                </txp:smd_thumbnail>
            <txp:else />
                <img itemprop="url" alt="<txp:image_info type='alt' />" src="<txp:image_url />">
            </txp:smd_if_thumbnail>
        </p>
    </txp:images>

Tag error is: "Notice: Undefined variable: alt while parsing form blog on page blog".

Any idea why this is happening. Is it an issue? I've tried the `type='alt'` with both single and double quotes but that hasn't helped.

**Comment by Bloke** [comment]
Thanks for the report. Fixed.

**Comment by philwareham** [comment]
Great, any chance of a new beta release?

**Comment by phiw13** [comment]
I had reported this issue months ago in the forums: https://forum.textpattern.io/viewtopic.php?pid=303721#p303721

glad to see it solved.

**Comment by Bloke** [comment]
@phiw13 Sorry, I missed that.
