### ISSUE TITLE
Re-assign Textpack group

### ISSUE THREAD

**Issue by jools-r** [Bloke/smd_thumbnail#27]
Minor tweak: For the textpack strings to show properly on Textpattern v4.8.5 (perhaps earlier too) it looks like you now need:

```
#@owner smd_thumb
#@admin-side
#@language en
…
#@language fr
…
#@language de
…
```

at the start of the Textpack.

**Comment by Bloke** [comment]
Hmmm, where do you see untranslated strings? In theory, when we tighten the plugin language loading system in future (currently all plugin strings are loaded all the time) then the pack will need to be:

~~~
#@owner smd_thumb
#@image
#@language en
...
~~~

I've done that in b98fda45.
