### ISSUE TITLE
Avif support in 4.8.8

### ISSUE THREAD

**Issue by phiw13** [Bloke/smd_thumbnail#29]
Plugin need some love to support AVIF images where/when supported TXP 4.8.8 / PHP 8.1 / GD 2.3.3 with support build in. Probably something similar as the .webp support checks

```
if (isset($gd_info['WebP Support']) && $gd_info['WebP Support']) {
        $valid_exts['.webp'] = IMAGETYPE_WEBP;
    }
```

**Comment by Bloke** [comment]
[Try now](https://github.com/Bloke/smd_thumbnail/commit/9f878d4c814a747401442055084fdd0f9642ec85)

**Comment by phiw13** [comment]
Hmm. Not sure. I see the same process as described in the forum (no feedback at all, no listing of the uploaded image) in both Safari and Firefox. And no thumbnails generated. The image is still uploaded though.

There might be some more issues with AVIF at the core level as thumbnail generation fails without the plugin and with the plugin with lots of error babble. I will post a follow up message in the forum later tonight.

**Comment by Bloke** [comment]
Okay cool, thanks. I'll keep an eye out.

**Comment by phiw13** [comment]
With PHP 8.1. only the default action (create thumbs on upload) seem to work (TXP 4.8.8). With PHP 8.2, all actions on edit image panel (create/delete/upload) work here (TXP 4.9-dev, though).
