### ISSUE TITLE
Provide some example usage cases in the README

### ISSUE THREAD

**Issue by philwareham** [Bloke/smd_thumbnail#3]
It would be real handy to have some usage examples included in the README file. Can be a bit confusing for users (i.e. me) to get our heads around initially - so totes moar infoz is alwayz good, innit?

**Comment by Bloke** [comment]
Noted. Examples sorely lacking.

**Comment by philwareham** [comment]
A nice fleshed out example [of this](http://forum.textpattern.com/viewtopic.php?pid=288361#p288361) would be helpful to users, plus any other handy snippets mentioned in the forum thread. Not too easy to find them quickly amongst ~30 pages of forum thread.

**Comment by Bloke** [comment]
Closed by 472d7eb18 and 648269f6.
