### ISSUE TITLE
TXP4.9-dev + strict CSP - create thumbnail fails on edit image panel

### ISSUE THREAD

**Issue by phiw13** [Bloke/smd_thumbnail#31]
Environment: TXP-dev 4.9 + PHP 8.2

STR:
* turn ON a strict CSP for the admin side in `config.php`, the provided settings should be OK.
* on the admin Panel > images, select an image to edit
* Try to create or delete or upload a thumbnail image.

**Result**: failure. The select menu changes value as displayed, nothing happens further.
The action is triggered by an event handler (`onchange`) on the select widget, which is blocked by the CSP settings (`script-src-attr 'none'`).

The js event handler in full: `onchange="return smd_thumb_select_changed()"`

Possible solutions: 
* the user can eventually generate a hash for that event handler and add it to the CSP policy in use.
* modify the JS to remove the need for said inline handler

Note: the plugin does its job when uploading an image

PS - I noticed that the `<style />` block for the extension is blocked as well (the nonce is not applied), but that is possibly a core issue.

**Comment by Bloke** [comment]
I has this yesterday with smd_tags too. The inline style block was being blocked by CSP and causing the plugin to not function. I'll patch this the same way.
Thank you for the report.

**Comment by phiw13** [comment]
There are more inline js event thingies – on the main images panel, both under profiles and setup. All fail(=do nothing) when a strict CSP is used.

* below the list of profiles: `<a class="txp-button" href="#" onclick="return smd_thumb_togglenew();">New profile</a>`
* the “active profile” checkbox: `<input type="checkbox" name="smd_thumb_active_medium" value="1" checked="checked" class="checkbox" onchange="smd_thumb_switch_active('medium');" />`
* setup screen `onclick="smd_thumb_copy_selected(); return confirm('Really create thumbnails for ALL active profiles? Any existing thumbs will be overwritten.');"`
* setup screen, checkboxes: `onchange="smd_thumb_switch_pref(this, 'auto_replace');"`

**Comment by phiw13** [comment]
The issue with the style block is indeed surprisingly easy to solve. diff:

```
@@ -98,7 +98,13 @@
 
     if ($event === 'image') {
         $smd_thumb_styles = smd_thumb_get_style_rules();
-        echo '<style type="text/css">', $smd_thumb_styles['smd_thumb'], '</style>';
+        $content = $smd_thumb_styles['smd_thumb'];
+        if (class_exists('\Textpattern\UI\Style')) {
+                echo Txp::get('\Textpattern\UI\Style')->setContent($content);
+            } else {
+                echo '<style>' . $content . '</style>';
+            }
     }
```

**Comment by Bloke** [comment]
Yep, that's the perfect approach. I'll fix this, thank you (or if you fancy preparing a PR, I'll merge it).

**Comment by phiw13** [comment]
> I'll fix this, thank you (or if you fancy preparing a PR, I'll merge it).

Nah, go ahead – I haven’t figured  out how to fix all those `onchange` and `onclick` inline js thingies (I got  lost somewhere).

**Comment by phiw13** [comment]
And then there is this one line:
https://github.com/Bloke/smd_thumbnail/blob/master/smd_thumbnail.php#L773

```
<script>
window.location.href="{$url}";
</script>
```

(the reason I had some problem yesterday)
